[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"
vicmd_symbol = "[<](bold green)"

[line_break]
disabled = true

[cmd_duration]
min_time = 500
format = "underwent [$duration](bold yellow)"

[git_commit]
tag_symbol = " tag "

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"

[aws]
symbol = "aws "

[c]
symbol = "C "

[hostname]
ssh_only = false
format = "[$ssh_symbol](bold blue)@[$hostname](bold red) "
trim_at = "."
disabled = false

[conda]
symbol = "conda "

[crystal]
symbol = "cr "

[cmake]
symbol = "cmake "

[daml]
symbol = "daml "

[dart]
symbol = "dart "

[deno]
symbol = "deno "

[dotnet]
symbol = ".NET "

[directory]
read_only = " ro"
truncation_length = 8
truncation_symbol = ".../"

[docker_context]
symbol = "docker "

[elixir]
symbol = "exs "

[elm]
symbol = "elm "

[git_branch]
symbol = "git "

[golang]
symbol = "go "

[hg_branch]
symbol = "hg "

[java]
symbol = "java "

[nodejs]
symbol = "nodejs "

[memory_usage]
symbol = "memory "

[nim]
symbol = "nim "

[ocaml]
symbol = "ml "

[package]
symbol = "pkg "

[perl]
symbol = "pl "

[php]
symbol = "php "

[python]
symbol = "py "

[ruby]
disabled = true

[rust]
symbol = "rs "

[scala]
symbol = "scala "

[shell]
bash_indicator = "bsh"
powershell_indicator = "_"
unknown_indicator = "mystery shell"
style = "cyan bold"
format = "[$indicator]($style) "
disabled = true

[spack]
symbol = "spack "

[sudo]
symbol = "sudo "

[swift]
symbol = "swift "

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style)"
disabled = false
show_always = true
